/*
Typewriter 2021 Muvaffak Onus.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typewriter. DO NOT EDIT.

package producer

import (
	app "github.com/muvaf/typewriter/examples/producer/app"
	db "github.com/muvaf/typewriter/examples/producer/db"
)

// GenerateUserV1 returns a new db.UserV1 with the information from
// given app.UserAll.
func GenerateUserV1(a app.UserAll) db.UserV1 {
	b := db.UserV1{}
	b.Name = a.Name
	b.Surname = a.Surname
	b.Identifier = a.Identifier
	if len(a.Belongings) != 0 {
		b.Belongings = make([]db.BelongingV1, len(a.Belongings))
		for v0 := range a.Belongings {
			if len(a.Belongings[v0].Automobiles) != 0 {
				b.Belongings[v0].Automobiles = make([]string, len(a.Belongings[v0].Automobiles))
				for v1 := range a.Belongings[v0].Automobiles {
					b.Belongings[v0].Automobiles[v1] = a.Belongings[v0].Automobiles[v1]
				}
			}
		}
	}
	return b
}

// GenerateUserV2 returns a new db.UserV2 with the information from
// given app.UserAll.
func GenerateUserV2(a app.UserAll) db.UserV2 {
	b := db.UserV2{}
	b.Name = a.Name
	b.Id = a.Id
	b.UserGroup = a.UserGroup
	if len(a.Belongings) != 0 {
		b.Belongings = make([]db.BelongingV2, len(a.Belongings))
		for v0 := range a.Belongings {
			if len(a.Belongings[v0].Cars) != 0 {
				b.Belongings[v0].Cars = make([]string, len(a.Belongings[v0].Cars))
				for v1 := range a.Belongings[v0].Cars {
					b.Belongings[v0].Cars[v1] = a.Belongings[v0].Cars[v1]
				}
			}
		}
	}
	return b
}
