/*
Typewriter 2021 Muvaffak Onus.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by typewriter. DO NOT EDIT.

package producer

import (
	app "github.com/muvaf/typewriter/examples/producer/app"
	sdk "github.com/muvaf/typewriter/examples/producer/sdk"
)

// GenerateSDKUser returns a new sdk.SDKUser with the information from
// given app.User.
func GenerateSDKUser(a app.User) sdk.SDKUser {
	b := sdk.SDKUser{}
	b.Name = a.Name
	b.Id = a.Id
	if len(a.Belongings) != 0 {
		b.Belongings = make([]sdk.SDKBelonging, len(a.Belongings))
		for v0 := range a.Belongings {
			if len(a.Belongings[v0].Cars) != 0 {
				b.Belongings[v0].Cars = make([]string, len(a.Belongings[v0].Cars))
				for v1 := range a.Belongings[v0].Cars {
					b.Belongings[v0].Cars[v1] = a.Belongings[v0].Cars[v1]
				}
			}
		}
	}
	return b
}
